### ISSUE TITLE
Filter by title does not work.

### ISSUE THREAD

**Issue by tetranz** [webkulabhi/magento2-create-admin-grid-CURD-operations#3]
Thanks for this example, it's been very helpful.

Filter by title does not seem to work. It has no affect on the result.

It does work if I change textRange to text in line 131 of grid_record_grid_list.xml.  That gives a single textbox which I guess is doing a "starts with" filter. That's quite usable but it would be nice to get the range working.

dataRange on publish_date seems to work correctly.

**Comment by webkulabhi** [comment]
@tetranz thanks for report issues. issues fixed.
