### ISSUE TITLE
Other module artifacts/remnants

### ISSUE THREAD

**Issue by bhapps** [webkulabhi/magento2-create-admin-grid-CURD-operations#4]
Hi Webkul,

Whats with all the misc code files inside the module, i.e ebay files etc below;

https://github.com/webkulabhi/magento2-create-admin-grid-CURD-operations/tree/master/view/adminhtml/templates

**Comment by webkulabhi** [comment]
Hi Bennith,
By mistake some unwanted files pushed on repo. Now they are removed.
Thanks for report.

**Comment by bhapps** [comment]
Thanks for your quick response

**Comment by webkulabhi** [comment]
Welcome
